import { fileURLToPath } from "node:url";
import { mkdtemp, mkdir, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, expect, test, vi } from "vitest";
import { SessionManager, SessionHub, inMemoryFrameSpool, HistoryService } from "../src/index.js";
import type { FrameSpool, ServerFrame } from "../src/index.js";
import { encodeProjectDir } from "@remote-coder/protocol";

const MOCK = fileURLToPath(new URL("./helpers/mock-claude-interactive.mjs", import.meta.url));

function hubFor(mode: string, opts: { spool?: FrameSpool; history?: HistoryService } = {}) {
  const manager = new SessionManager(
    { claudeBin: process.execPath },
    { spawnPrefixArgs: [MOCK], baseEnv: { ...process.env, MOCK_MODE: mode }, startTimeoutMs: 5000 },
  );
  return { hub: new SessionHub(manager, opts), manager };
}

// Temp claudeHome(s) created for the HistoryService-backed rewind tests; torn down after each.
const tmpHomes: string[] = [];
afterEach(async () => {
  while (tmpHomes.length) await rm(tmpHomes.pop()!, { recursive: true, force: true });
});

/** A fresh temp claudeHome + a HistoryService over it. The transcript is written separately (after the
 *  session id is known) via `writeTranscript`, since the id is generated by createSession. */
async function freshHistory(): Promise<{ claudeHome: string; history: HistoryService }> {
  const claudeHome = await mkdtemp(join(tmpdir(), "rc-rewind-home-"));
  tmpHomes.push(claudeHome);
  return { claudeHome, history: new HistoryService({ claudeHome }) };
}

/** Write a fixture transcript naming `id` at `cwd` under an existing claudeHome (read fresh on each call). */
async function writeTranscript(claudeHome: string, cwd: string, id: string, lines: string): Promise<void> {
  const dir = join(claudeHome, ".claude", "projects", encodeProjectDir(cwd));
  await mkdir(dir, { recursive: true });
  await writeFile(join(dir, `${id}.jsonl`), lines);
}

function waitForFrame(hub: SessionHub, id: string, pred: (f: ServerFrame) => boolean): Promise<ServerFrame> {
  return new Promise((resolve) => {
    const sub = hub.subscribe(id, (f) => {
      if (pred(f)) {
        sub.unsubscribe();
        resolve(f);
      }
    });
  });
}

test("rewind code: live rewind_files on the running process, success + a rewound frame", async () => {
  const { hub, manager } = hubFor("simple");
  const meta = await hub.createSession({ cwd: process.cwd() });
  const proc = manager.getSession(meta.id)!.process;
  const spy = vi.spyOn(proc, "rewindFiles");

  const rewoundPromise = waitForFrame(hub, meta.id, (f) => f.kind === "rewound");
  const result = await hub.rewind(meta.id, "uuid-cp", "code");

  expect(result.ok).toBe(true);
  expect(result.canRewind).toBe(true);
  expect(spy).toHaveBeenCalledWith("uuid-cp", {});

  const frame = await rewoundPromise;
  expect(frame.payload).toMatchObject({ checkpointId: "uuid-cp", mode: "code", ok: true });
  // code mode does NOT respawn the process.
  expect(manager.getSession(meta.id)).toBeDefined();

  hub.stopSession(meta.id);
});

test("rewind conversation: stops the live process and resumes it truncated at the checkpoint", async () => {
  const { hub, manager } = hubFor("simple");
  const meta = await hub.createSession({ cwd: process.cwd() });
  const resumeSpy = vi.spyOn(manager, "resumeSession");

  const rewoundPromise = waitForFrame(hub, meta.id, (f) => f.kind === "rewound");
  const result = await hub.rewind(meta.id, "uuid-cp", "conversation");

  expect(result.ok).toBe(true);
  // It resumed with --resume-session-at <uuid> but NOT --rewind-files (conversation-only).
  expect(resumeSpy).toHaveBeenCalledTimes(1);
  expect(resumeSpy.mock.calls[0]![1]).toMatchObject({ resumeSessionAt: "uuid-cp" });
  expect(resumeSpy.mock.calls[0]![1].rewindFilesAt).toBeUndefined();

  const frame = await rewoundPromise;
  expect(frame.payload).toMatchObject({ checkpointId: "uuid-cp", mode: "conversation", ok: true });
  // The session is live again (resumed) and not flagged errored.
  expect(hub.getSession(meta.id)?.status).toBe("running");

  hub.stopSession(meta.id);
});

test("rewind both: reverts files via a LIVE rewindFiles(M) then resumes the conversation (no resume-time --rewind-files)", async () => {
  const { hub, manager } = hubFor("simple");
  const meta = await hub.createSession({ cwd: process.cwd() });
  const resumeSpy = vi.spyOn(manager, "resumeSession");
  const rewindFilesSpy = vi.spyOn(manager, "rewindFiles");

  const result = await hub.rewind(meta.id, "uuid-cp", "both");
  expect(result.ok).toBe(true);
  // Files reverted via the live control request at M (a valid file checkpoint)...
  expect(rewindFilesSpy).toHaveBeenCalledWith(meta.id, "uuid-cp");
  // ...and the conversation resumed (no HistoryService here → resumeAt falls back to M); the resume-time
  // --rewind-files flag is NOT used (it's incompatible with resuming at the parent).
  expect(resumeSpy.mock.calls[0]![1]).toMatchObject({ resumeSessionAt: "uuid-cp" });
  expect(resumeSpy.mock.calls[0]![1].rewindFilesAt).toBeUndefined();

  hub.stopSession(meta.id);
});

test("rewind code on a disabled-checkpointing CLI resolves ok:false and still emits a rewound frame", async () => {
  const { hub } = hubFor("rewind-disabled");
  const meta = await hub.createSession({ cwd: process.cwd() });

  const rewoundPromise = waitForFrame(hub, meta.id, (f) => f.kind === "rewound");
  const result = await hub.rewind(meta.id, "uuid-cp", "code");
  expect(result.ok).toBe(false);
  expect(result.error).toBe("File rewinding is not enabled.");

  const frame = await rewoundPromise;
  expect(frame.payload).toMatchObject({ checkpointId: "uuid-cp", mode: "code", ok: false });

  hub.stopSession(meta.id);
});

test("rewind throws for an unknown session id (consistent with other hub ops)", async () => {
  const { hub } = hubFor("simple");
  await expect(hub.rewind("nope", "uuid", "code")).rejects.toThrow(/unknown session/);
});

// EDIT & RESEND (B1): a conversation rewind resumes at the checkpoint's PARENT uuid (the line right before
// M) so M is actually DROPPED — while the emitted `rewound` frame still carries the ORIGINAL checkpointId.
test("rewind conversation resumes at the checkpoint's PARENT uuid (so M is dropped), frame keeps M's id", async () => {
  const cwd = process.cwd();
  const { claudeHome, history } = await freshHistory();
  const { hub, manager } = hubFor("simple", { history });
  // Create the session FIRST (so we have its real id), then write a fixture transcript naming that id —
  // the HistoryService reads the file fresh, so writing after creation is fine.
  const meta = await hub.createSession({ cwd });
  await writeTranscript(
    claudeHome,
    cwd,
    meta.id,
    [
      JSON.stringify({ type: "user", uuid: "u1", parentUuid: "boot", message: { role: "user", content: "M1" } }),
      JSON.stringify({
        type: "assistant",
        uuid: "a1",
        parentUuid: "u1",
        message: { role: "assistant", content: "R1" },
      }),
      JSON.stringify({ type: "user", uuid: "cp-M", parentUuid: "a1", message: { role: "user", content: "the edit" } }),
    ].join("\n"),
  );
  const resumeSpy = vi.spyOn(manager, "resumeSession");

  const rewoundPromise = waitForFrame(hub, meta.id, (f) => f.kind === "rewound");
  const result = await hub.rewind(meta.id, "cp-M", "conversation");
  expect(result.ok).toBe(true);
  // It resumed at cp-M's PARENT (a1), NOT cp-M — so the rewound message itself is dropped.
  expect(resumeSpy).toHaveBeenCalledTimes(1);
  expect(resumeSpy.mock.calls[0]![1]).toMatchObject({ resumeSessionAt: "a1" });

  // The emitted rewound frame still carries the ORIGINAL checkpointId (M) for the client truncation.
  const frame = await rewoundPromise;
  expect(frame.payload).toMatchObject({ checkpointId: "cp-M", mode: "conversation", ok: true });

  hub.stopSession(meta.id);
});

test("rewind both: resume at the PARENT (drop M) but rewind-files at M itself (a valid file checkpoint)", async () => {
  const cwd = process.cwd();
  const { claudeHome, history } = await freshHistory();
  const { hub, manager } = hubFor("simple", { history });
  const meta = await hub.createSession({ cwd });
  await writeTranscript(
    claudeHome,
    cwd,
    meta.id,
    [
      JSON.stringify({
        type: "assistant",
        uuid: "a1",
        parentUuid: "u1",
        message: { role: "assistant", content: "R1" },
      }),
      JSON.stringify({ type: "user", uuid: "cp-M", parentUuid: "a1", message: { role: "user", content: "edit" } }),
    ].join("\n"),
  );
  const resumeSpy = vi.spyOn(manager, "resumeSession");
  const rewindFilesSpy = vi.spyOn(manager, "rewindFiles");
  const result = await hub.rewind(meta.id, "cp-M", "both");
  expect(result.ok).toBe(true);
  // Files reverted via a LIVE rewindFiles at M itself (cp-M, a valid file checkpoint) BEFORE the respawn;
  // the conversation then resumes at the PARENT (a1) to drop M. The parent is an assistant uuid, not a
  // valid file checkpoint, so it's never passed to --rewind-files (claude would exit before init).
  expect(rewindFilesSpy).toHaveBeenCalledWith(meta.id, "cp-M");
  expect(resumeSpy.mock.calls[0]![1]).toMatchObject({ resumeSessionAt: "a1" });
  expect(resumeSpy.mock.calls[0]![1].rewindFilesAt).toBeUndefined();
  hub.stopSession(meta.id);
});

test("rewind conversation FALLS BACK to resuming at M when the parent can't be resolved (no hard-fail)", async () => {
  // No HistoryService configured → parentUuidOf can't run → resume at M itself (prior behavior). This is
  // the safety net so a rewind never hard-fails on an unresolved checkpoint.
  const { hub, manager } = hubFor("simple");
  const meta = await hub.createSession({ cwd: process.cwd() });
  const resumeSpy = vi.spyOn(manager, "resumeSession");
  const result = await hub.rewind(meta.id, "uuid-cp", "conversation");
  expect(result.ok).toBe(true);
  expect(resumeSpy.mock.calls[0]![1]).toMatchObject({ resumeSessionAt: "uuid-cp" });
  hub.stopSession(meta.id);
});

// LOW-1: a conversation rewind DROPS every turn after the checkpoint, so the spool's post-checkpoint
// in-flight tail is now stale — it must be cleared so a reopen before the next result can't resurrect it.
test("rewind conversation CLEARS the spool (pre-rewind in-flight content can't resurrect on reopen)", async () => {
  const spool = inMemoryFrameSpool();
  const { hub } = hubFor("simple", { spool });
  const meta = await hub.createSession({ cwd: process.cwd() });
  // Seed a spooled in-flight tail (a uuid-bearing assistant frame, the only spoolable event shape).
  spool.append(meta.id, {
    seq: 0,
    kind: "event",
    payload: { type: "assistant", uuid: "pre-rewind", message: { content: [{ type: "text", text: "stale tail" }] } },
  });
  expect(spool.read(meta.id).length).toBeGreaterThan(0);

  await hub.rewind(meta.id, "uuid-cp", "conversation");
  // The PRE-rewind in-flight tail is gone (cleared before the respawn) — it can't resurrect on reopen.
  // (The post-rewind `rewound` marker the handler emits legitimately re-spools; that's the new boundary.)
  const after = spool.read(meta.id);
  expect(after.some((f) => (f.payload as { uuid?: string }).uuid === "pre-rewind")).toBe(false);

  hub.stopSession(meta.id);
  spool.close();
});

// `code` rewind leaves the conversation intact, so its spool must NOT be cleared.
test("rewind code does NOT clear the spool (the conversation is unchanged)", async () => {
  const spool = inMemoryFrameSpool();
  const { hub } = hubFor("simple", { spool });
  const meta = await hub.createSession({ cwd: process.cwd() });
  spool.append(meta.id, {
    seq: 0,
    kind: "event",
    payload: { type: "assistant", uuid: "keep", message: { content: [{ type: "text", text: "tail" }] } },
  });
  await hub.rewind(meta.id, "uuid-cp", "code");
  expect(spool.read(meta.id).length).toBeGreaterThan(0); // code rewind leaves the spool intact

  hub.stopSession(meta.id);
  spool.close();
});
